### ISSUE TITLE
Index out of range: no indices are valid: 0

### ISSUE THREAD

**Issue by vanlooverenkoen** [llfbandit/dio_cache_interceptor#31]
```
  Future<DioCacheInterceptor> provideDioCacheInterceptor() async {
    final appDocDir = await getApplicationDocumentsDirectory();
    final options = CacheOptions(
      store: FileCacheStore('${appDocDir.path}/cache'),
      policy: CachePolicy.request,
      maxStale: const Duration(days: 90),
      priority: CachePriority.normal,
      keyBuilder: CacheOptions.defaultCacheKeyBuilder,
      allowPostMethod: false,
    );
    return DioCacheInterceptor(options: options);
  }
```

The exception:
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: RangeError (index): Index out of range: no indices are valid: 0. Error thrown null.
       at _Int32ArrayView.[](_Int32ArrayView.java)
       at FileCacheStore._deserializeContent(FileCacheStore.java:147)
       at FileCacheStore.get(FileCacheStore.java:61)
       at DioCacheInterceptor._getCacheResponse(DioCacheInterceptor.java:270)
       at DioCacheInterceptor._getResponse(DioCacheInterceptor.java:284)
       at DioCacheInterceptor.onError(DioCacheInterceptor.java:125)
       at DioMixin.fetch._errorInterceptorWrapper.<fn>.<fn>.<fn>(<fn>.java:557)
       at DioMixin.checkIfNeedEnqueue(DioMixin.java:795)
       at DioMixin.fetch._errorInterceptorWrapper.<fn>.<fn>(<fn>.java:555)
       at _CustomZone.bindCallback.<fn>(bindCallback.java)
       at safeRun.<fn>(safeRun.java:7)
```

I got this error in firebase. I can not reproduce
- samsung j6
- huawei P9 lite
- iPhone 8 
- iPhone 8 plus

**Comment by andreacimino** [comment]
I have the same kind of Issue, but seems the stack is different:


```
IndexError
RangeError (index): Index out of range: no indices are valid: 0

file_cache_store_io.dart in FileCacheStore._deserializeContent at line 147 within dio_cache_interceptor
file_cache_store_io.dart in FileCacheStore._deleteFile at line 217 within dio_cache_interceptor
file_cache_store_io.dart in FileCacheStore.clean.<fn>.<fn> at line 32 within dio_cache_interceptor
file_cache_store_io.dart in FileCacheStore.clean.<fn>.<fn> at line 31 within dio_cache_interceptor
Called from: growable_array.dart in _GrowableList.forEach
file_cache_store_io.dart in FileCacheStore.clean.<fn> at line 31 within dio_cache_interceptor
file_cache_store_io.dart in FileCacheStore.clean.<fn> at line 26 within dio_cache_interceptor
Called from: iterable.dart in _GeneratorIterable.elementAt
file_cache_store_io.dart in FileCacheStore.clean at line 43 within dio_cache_interceptor
file_cache_store_io.dart in new FileCacheStore at line 18 within dio_cache_interceptor
```

The error happens (at least in my logs) if the app is resumed.
: AppLifecycleState.resumed

initial_lifecycle_state |  
-- | --


<br class="Apple-interchange-newline">


initial_lifecycle_state |  
-- | --


<br class="Apple-interchange-newline">

**Comment by llfbandit** [comment]
File concurrent access is now fixed. File cache store is now external.
https://pub.dev/packages/dio_cache_interceptor_file_store

**Comment by vanlooverenkoen** [comment]
We just updated to the latest version. We are using obfuscation now in our app. Because 90% of our non fatal crashes were caused by dio_cache_interceptor we will probably see if the error goes crash rate goes down or not. We will keep you posted

**Comment by llfbandit** [comment]
Thanks for using this package and your patience for this fix.
Feedback is always welcome for sure!

**Comment by vanlooverenkoen** [comment]
Still having the same issue.

**Comment by vanlooverenkoen** [comment]
After deobfuscation I get this:

```
Non-fatal Exception: FlutterError
0  ???                            0x0 (null).#0      _Int32ArrayView.[] (dart:typed_data-patch/typed_data_patch.dart:4372:7)
0  ???                            0x0 (null).#1      FileCacheStore._deserializeContent (package:dio_cache_interceptor_file_store/src/store/dio_cache_interceptor_file_store_io.dart:166:21)
1  ???                            0x0 (null).#2      FileCacheStore.get.<anonymous closure> (package:dio_cache_interceptor_file_store/src/store/dio_cache_interceptor_file_store_io.dart:61:20)
2  ???                            0x0 (null).#3      ReentrantLock.synchronized.<anonymous closure> (package:synchronized/src/reentrant_lock.dart:37:18)
3  ???                            0x0 (null).#4      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
4  ???                            0x0 (null).#5      FileCacheStore._synchronized (package:dio_cache_interceptor_file_store/src/store/dio_cache_interceptor_file_store_io.dart:106:20)
5  ???                            0x0 (null).#6      DioCacheInterceptor._getCacheResponse (package:dio_cache_interceptor/src/dio_cache_interceptor.dart:270:20)
6  ???                            0x0 (null).#7      DioCacheInterceptor.onRequest (package:dio_cache_interceptor/src/dio_cache_interceptor.dart:41:25)
```

**Comment by llfbandit** [comment]
I suggest you to cleanup your store before.
The fix does not look for corrupted files.

**Comment by llfbandit** [comment]
When you app starts, don't you have upgrade process?
This should be done only once.

**Comment by vanlooverenkoen** [comment]
Alright yes that was what I needed to know. 
The cleanup should be done with every update of dio_cache_interceptor? or only this time?

**Comment by llfbandit** [comment]
Only this time, to throw away any corrupted file (and valid ones also I'm afraid... :/).
`store.clean();` should do it.

**Comment by vanlooverenkoen** [comment]
Alright it doesn't matter if it is removed 1 time. Our valid duration is only 24hours so they will have to redownload the file anyway in a couple of hours.

**Comment by llfbandit** [comment]
Download file???
In the coming version which will be published in fex days, any response with `content-disposition: attachment, ...` won't be stored in cache.

Is it really your case?

**Comment by vanlooverenkoen** [comment]
No our cache is only valid for 24 hour. that was a requirement from business :)
